import Map from '@/components/Map/Map';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex align-middle flex-row">
                    <div>{children}</div>
                    <Map />
                </div>
            </body>
        </html>
    );
}
