import Map from '@/components/Map/Map';
import './globals.css';

export const metadata = {
    title: 'Pub Ranker',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div className="flex align-middle flex-row ">
                    <div className="shadow-lg h-screen w-96">{children}</div>
                    <Map />
                </div>
            </body>
        </html>
    );
}
